SmartStoreNET-4.x/src/Presentation/SmartStore.Web/Administration/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Text;
using System.Web.Mvc;
using SmartStore.Admin.Models.DataExchange;
using SmartStore.Admin.Models.Tasks;
using SmartStore.Core;
using SmartStore.Core.Domain;
using SmartStore.Core.Domain.DataExchange;
using SmartStore.Core.Domain.Tasks;
using SmartStore.Core.IO;
using SmartStore.Core.Security;
using SmartStore.Services.Catalog.Importer;
using SmartStore.Services.Customers.Importer;
using SmartStore.Services.DataExchange.Csv;
using SmartStore.Services.DataExchange.Import;
using SmartStore.Services.Localization;
using SmartStore.Services.Messages.Importer;
using SmartStore.Services.Tasks;
using SmartStore.Utilities;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Filters;
using SmartStore.Web.Framework.Security;

namespace SmartStore.Admin.Controllers
{
    [AdminAuthorize]
    public class ImportController : AdminControllerBase
    {
        private readonly IImportProfileService _importProfileService;
        private readonly ITaskScheduler _taskScheduler;
        private readonly IScheduleTaskService _scheduleTaskService;
        private readonly AdminModelHelper _adminModelHelper;

        public ImportController(
            IImportProfileService importService,
            ITaskScheduler taskScheduler,
            IScheduleTaskService scheduleTaskService,
            AdminModelHelper adminModelHelper)
        {
            _importProfileService = importService;
            _taskScheduler = taskScheduler;
            _scheduleTaskService = scheduleTaskService;
            _adminModelHelper = adminModelHelper;
        }

        #region Utilities

        private bool IsValidImportFile(string path, out string error)
        {
            error = null;

            try
            {
                using (var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
                {
                    var unused = LightweightDataTable.FromFile(path, stream, stream.Length, CsvConfiguration.ExcelFriendlyConfiguration, 0, 1);
                }

                return true;
            }
            catch (Exception ex)
            {
                error = ex.ToAllMessages();
                FileSystemHelper.DeleteFile(path);
                return false;
            }
        }

        private bool IsDefaultValueDisabled(string column, string property, string[] disabledFieldNames)
        {
            if (disabledFieldNames.Contains(property))
                return true;

            string columnWithoutIndex, columnIndex;
            if (ColumnMap.ParseSourceName(property, out columnWithoutIndex, out columnIndex))
                return disabledFieldNames.Contains(columnWithoutIndex);

            return false;
        }

        private string[] GetDisabledDefaultFieldNames(ImportProfile profile)
        {
            switch (profile.EntityType)
            {
                case ImportEntityType.Product:
                    return new string[] { "Name", "Sku", "ManufacturerPartNumber", "Gtin", "SeName" };
                case ImportEntityType.Category:
                    return new string[] { "Name", "SeName" };
                case ImportEntityType.Customer:
                    return new string[] { "CustomerGuid", "Email" };
                case ImportEntityType.NewsLetterSubscription:
                    return new string[] { "Email" };
                default:
                    return new string[0];
            }
        }

        private string GetPropertyDescription(Dictionary<string, string> allProperties, string property)
        {
            if (property.HasValue() && allProperties.ContainsKey(property))
            {
                var result = allProperties[property];
                if (result.HasValue())
                    return result;
            }
            return property;
        }

        private void PrepareProfileModel(
            ImportProfileModel model,
            ImportProfile profile,
            ScheduleTaskHistory lastHistoryEntry,
            bool forEdit,
            ColumnMap invalidMap = null)
        {
            model.Id = profile.Id;
            model.Name = profile.Name;
            model.EntityType = profile.EntityType;
            model.Enabled = profile.Enabled;
            model.ImportRelatedData = profile.ImportRelatedData;
            model.Skip = profile.Skip == 0 ? (int?)null : profile.Skip;
            model.Take = profile.Take == 0 ? (int?)null : profile.Take;
            model.UpdateOnly = profile.UpdateOnly;
            model.KeyFieldNames = profile.KeyFieldNames.SplitSafe(",").Distinct().ToArray();
            model.ScheduleTaskId = profile.SchedulingTaskId;
            model.ScheduleTaskName = profile.ScheduleTask.Name.NaIfEmpty();
            model.IsTaskRunning = lastHistoryEntry?.IsRunning ?? false;
            model.IsTaskEnabled = profile.ScheduleTask.Enabled;
            model.LogFileExists = System.IO.File.Exists(profile.GetImportLogPath());
            model.EntityTypeName = profile.EntityType.GetLocalizedEnum(Services.Localization, Services.WorkContext);
            model.ExistingFiles = profile.GetImportFiles();

            foreach (var file in model.ExistingFiles)
            {
                if (file.RelatedType.HasValue)
                {
                    file.Label = string.Concat(T("Admin.Common.Data"), " ", file.RelatedType.Value.GetLocalizedEnum(Services.Localization, Services.WorkContext));
                }
            }

            if (profile.ResultInfo.HasValue())
            {
                model.ImportResult = XmlHelper.Deserialize<SerializableImportResult>(profile.ResultInfo);
            }

            if (!forEdit)
            {
                return;
            }

            CsvConfiguration csvConfiguration = null;

            if (profile.FileType == ImportFileType.CSV)
            {
                var csvConverter = new CsvConfigurationConverter();
                csvConfiguration = csvConverter.ConvertFrom<CsvConfiguration>(profile.FileTypeConfiguration) ?? CsvConfiguration.ExcelFriendlyConfiguration;

                model.CsvConfiguration = new CsvConfigurationModel(csvConfiguration);
            }
            else
            {
                csvConfiguration = CsvConfiguration.ExcelFriendlyConfiguration;
            }

            // Common configuration.
            var extraData = XmlHelper.Deserialize<ImportExtraData>(profile.ExtraData);
            model.ExtraData.NumberOfPictures = extraData.NumberOfPictures;

            // Column mapping.
            model.AvailableSourceColumns = new List<ColumnMappingItemModel>();
            model.AvailableEntityProperties = new List<ColumnMappingItemModel>();
            model.AvailableKeyFieldNames = new List<SelectListItem>();
            model.ColumnMappings = new List<ColumnMappingItemModel>();

            model.FolderName = profile.GetImportFolder(absolutePath: false);

            try
            {
                string[] availableKeyFieldNames = null;
                string[] disabledDefaultFieldNames = GetDisabledDefaultFieldNames(profile);
                var mapConverter = new ColumnMapConverter();
                var storedMap = mapConverter.ConvertFrom<ColumnMap>(profile.ColumnMapping);
                var map = (invalidMap ?? storedMap) ?? new ColumnMap();

                // Property name to localized property name.
                var allProperties = _importProfileService.GetImportableEntityProperties(profile.EntityType);

                switch (profile.EntityType)
                {
                    case ImportEntityType.Product:
                        availableKeyFieldNames = ProductImporter.SupportedKeyFields;
                        break;
                    case ImportEntityType.Category:
                        availableKeyFieldNames = CategoryImporter.SupportedKeyFields;
                        break;
                    case ImportEntityType.Customer:
                        availableKeyFieldNames = CustomerImporter.SupportedKeyFields;
                        break;
                    case ImportEntityType.NewsLetterSubscription:
                        availableKeyFieldNames = NewsLetterSubscriptionImporter.SupportedKeyFields;
                        break;
                }

                model.AvailableEntityProperties = allProperties
                    .Select(x =>
                    {
                        var mapping = new ColumnMappingItemModel
                        {
                            Property = x.Key,
                            PropertyDescription = x.Value,
                            IsDefaultDisabled = IsDefaultValueDisabled(x.Key, x.Key, disabledDefaultFieldNames)
                        };

                        return mapping;
                    })
                    .ToList();

                model.AvailableKeyFieldNames = availableKeyFieldNames
                    .Select(x =>
                    {
                        var item = new SelectListItem { Value = x, Text = x };

                        if (x == "Id")
                            item.Text = T("Admin.Common.Entity.Fields.Id");
                        else if (allProperties.ContainsKey(x))
                            item.Text = allProperties[x];

                        return item;
                    })
                    .ToList();

                model.ColumnMappings = map.Mappings
                    .Select(x =>
                    {
                        var mapping = new ColumnMappingItemModel
                        {
                            Column = x.Value.MappedName,
                            Property = x.Key,
                            Default = x.Value.Default
                        };

                        if (x.Value.IgnoreProperty)
                        {

SmartStoreNET-4.x/src/Presentation/SmartStore.Web/Administration/Views/Import/Edit.cshtml
@using SmartStore.Admin.Models.DataExchange;
@model ImportProfileModel
@{
	var title = string.Concat(T("Common.Profile"), " - ", T("Admin.Common.Edit"));
	ViewBag.Title = title;
}

@using (Html.BeginForm())
{
	<fieldset>
		<div class="section-header">
			<div class="title">
				<i class="fa fa-download"></i>
				@title - @Model.Name @Html.ActionLink("(" + T("Admin.Common.BackToList") + ")", "List")
			</div>
			<div class="options">
				@if (Model.Id != 0)
                {
					<button type="button" id="ProfileImportButton" data-url="@Url.Action("Execute", "Import", new { area = "Admin", id = Model.Id })" class="btn btn-secondary">
						<i class="fa fa-cogs"></i>
						<span>@T("Common.Import")</span>
					</button>
                }
				@if (Model.LogFileExists)
                {
					<a href="@Url.Action("DownloadLogFile", new { id = Model.Id })" class="btn btn-secondary" target="LogFile">
						<i class="far fa-file-alt"></i>
						<span>@T("Admin.Configuration.ActivityLog")</span>
					</a>
                }
				<button type="submit" name="save" value="save" class="btn btn-primary">
					<i class="fa fa-check"></i>
					<span>@T("Admin.Common.Save")</span>
				</button>
				<button type="submit" name="save" value="save-continue" class="btn btn-secondary">
					<span>@T("Admin.Common.SaveContinue")</span>
				</button>
				<button type="submit" name="import-profile-delete" id="import-profile-delete" value="import-profile-delete" class="btn btn-danger">
					<i class="far fa-trash-alt"></i>
					<span>@T("Admin.Common.Delete")</span>
				</button>
			</div>
		</div>
		@{ Html.RenderPartial("_Update", Model); }
	</fieldset>
}
@Html.DeleteConfirmation("import-profile-delete")

SmartStoreNET-4.x/src/Presentation/SmartStore.Web/Administration/Views/Import/List.cshtml
@using SmartStore.Core.Domain.DataExchange;
@using SmartStore.Admin.Models.DataExchange;
@model ImportProfileListModel
@{
	ViewBag.Title = T("Common.Import").Text;
}

<div class="section-header">
    <div class="title">
		<i class="fa fa-download"></i>
        @T("Common.Import")
    </div>
    <div class="options">
        <a href="javascript:void(0)" data-url="@Url.Action("Create")" class="btn btn-primary import-profile-button">
			<i class="fa fa-plus"></i>
			<span>@T("Admin.Common.AddNew")</span>
		</a>
    </div>
</div>

@if(Model.Profiles.Any())
{
	<div class="table-responsive">
		<table id="import-profile-list" class="table admin-table">
			<thead>
				<tr>
					<th>@T("Admin.DataExchange.Import.Name")</th>
					<th>@T("Admin.Common.Entity")</th>
					<th>@T("Admin.Common.ImportFiles")</th>
					<th>@T("Admin.DataExchange.Import.LastImportResult")</th>
					<th>@T("Admin.System.ScheduleTasks.LastStart")</th>
					<th>@T("Admin.System.ScheduleTasks.NextRun")</th>
					<th>@T("Admin.Common.Actions")</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var profile in Model.Profiles)
				{
					<tr data-profile-id="@profile.Id" data-task-id="@profile.ScheduleTaskId" class="@(profile.Enabled ? "" : "disabled")">
						<td>
							<a href="@Url.Action("Edit", new { id = profile.Id })"><strong>@profile.Name</strong></a>
						</td>
						<td>
							@profile.EntityTypeName
						</td>
						<td>
							@if (profile.ExistingFiles.Any())
							{
								<ul class="fa-ul mb-0 ml-0">
									@foreach (var file in profile.ExistingFiles.Where(x => !x.RelatedType.HasValue))
									{
										<li title="@file.Name">
											@Html.IconForFileExtension(file.Extension, false)
											<a href="@Url.Action("DownloadImportFile", new { id = profile.Id, name = file.Name })" download>@file.Name</a>
										</li>
									}
								</ul>
							}

						</td>
						<td id="ProfileImportResult@(profile.Id)">
							@if (profile.ImportResult != null)
							{
								Html.RenderPartial("ProfileImportResult", profile.ImportResult);
							}
							else
							{
								<span class="muted">@("".NaIfEmpty())</span>
							}
						</td>
						<td>
							<div class="last-run-info">
								@{ Html.RenderPartial("~/Administration/Views/ScheduleTask/_LastRun.cshtml", profile.TaskModel); }
							</div>
						</td>
						<td class="progress-info">
							<div class="next-run-info">
								@{ Html.RenderPartial("~/Administration/Views/ScheduleTask/_NextRun.cshtml", profile.TaskModel); }
							</div>
							<div class="task-progress text-muted@(profile.IsTaskRunning ? "" : " d-none")" data-task-id="@profile.ScheduleTaskId" data-running="@(profile.IsTaskRunning ? "true" : "false")"></div>
						</td>
						<td style="width: 200px;" align="right" class="omega">
							<button type="button" class="btn btn-block btn-sm btn-warning btn-run-task@(profile.IsTaskRunning || !profile.Enabled ? " d-none" : "")"
									data-url="@Url.Action("Execute", "Import", new { area = "Admin", id = @profile.Id })" data-task-id="@profile.ScheduleTaskId">
								<i class="fa fa-play"></i>
								<span>@T("Admin.System.ScheduleTasks.RunNow")</span>
							</button>

							<a href="@Url.Action("CancelJob", "ScheduleTask", new { id = profile.ScheduleTaskId })" class="btn btn-block btn-sm btn-secondary btn-cancel-task@(!profile.IsTaskRunning ? " hide" : "")"
							   data-task-id="@profile.ScheduleTaskId" onclick='return confirm(@T("Admin.Common.AreYouSure").JsText);'>
								<span>@T("Common.Cancel")</span>
							</a>

							<a href="@Url.Action("DownloadLogFile", new { id = profile.Id })" target="LogFile"
							   class="btn btn-secondary btn-sm btn-block btn-log@(profile.IsTaskRunning || !profile.Enabled || !profile.LogFileExists ? " d-none" : "")">
								<i class="far fa-file-alt"></i>
								<span>@T("Admin.Configuration.ActivityLog")</span>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
}
else
{
	<div class="alert alert-info alert-dismissible">
		@T("Admin.DataExchange.Import.NoProfiles")
		<button type="button" class="close" data-dismiss="alert">&times;</button>
	</div>
}

@{Html.SmartStore().Window()
	.Name("import-profile-dialog")
	.Title(T("Common.Profile") + " - " + T("Admin.Common.AddNew"))
	.HtmlAttribute("data-profile", T("Common.Profile").Text)
	.Content(@<text>
        <form method="POST" action="@Url.Action("Create", "Import", new { area = "Admin" })" class="import-profile-form">
			<p class="text-muted">
				@T("Admin.DataExchange.Import.ProfileCreationNote")
			</p>
			<div>
				<div class="form-group">
					@Html.SmartLabelFor(x => x.EntityType)
					@Html.DropDownListFor(x => x.EntityType, Model.AvailableEntityTypes)
				</div>

				<div id="ImportFileUploadContainer">
					<input type="hidden" name="TempFileName" />
					@(Html.SmartStore().FileUploader()
						.Name("ImportFileUploader")
						.UploadUrl(Url.Action("FileUpload", new { id = Model.Id }))
						.AcceptedFileTypes("csv|xlsx|txt|tab")
						.ShowRemoveButton(false)
						.ShowRemoveButtonAfterUpload(false)
						.UploadText(T("Admin.DataExchange.Import.FileUpload").Text)
						.OnUploadCompletedHandlerName("onUploadCompleted")
					)
				</div>

				<div id="ImportFileList" class="hide">
					&nbsp;
				</div>
			</div>
        </form>
	</text>)
	.FooterContent(@<text>
		<button class="btn btn-secondary btn-flat" data-dismiss="modal">@T("Common.Cancel")</button>
		<button type="button" class="btn btn-primary" disabled="disabled">@T("Common.OK")</button>
	</text>)
	.Render();
}

<script>
	window['onUploadCompleted'] = function (e, el, data) {
		if (!_.isEmpty(data.result.tempFile)) {
			$('#import-profile-dialog').find('input[name=TempFileName]').val(data.result.tempFile);
			$('#ImportFileList').html(data.result.tempFile).show();
			$('#ImportFileUploadContainer').hide();		// just one initial file to specify the file type
			$('#import-profile-dialog').find('.btn-primary').prop('disabled', false);
		}
		else if (!_.isEmpty(data.result.error)) {
			$('#ImportFileList').html('<div class="alert alert-danger">' + data.result.error + '</div>').show();
		}
	}

	jQuery(document).ready(function () {

		// show profile dialog
		$(document).on('click', '.import-profile-button', function (e) {
			e.preventDefault();
			$('#import-profile-dialog').modal('show');
			return false;
        });

		// submit dialog form
        $('#import-profile-dialog').on('click', '.btn-primary', function () {
			$('#import-profile-dialog').find('.import-profile-form').submit();
		});

		// start task
		$(document).on('click', '.btn-run-task', function (e) {
			e.preventDefault();
			$(this).doPostData({
				ask: @T("Admin.Common.AskToProceed").JsText
			});
			return false;
		});

		SmartStore.Admin.TaskWatcher.startWatching({
			context: $('#import-profile-list'),
			elementsSelector: '.task-progress',
			defaultProgressMessage: @T("Admin.System.ScheduleTasks.RunNow.IsRunning").JsText,
			pollUrl: '@Url.Action("GetRunningTasks", "ScheduleTask")',
			onTaskStarted: function (task, el) {
				var tr = el.closest('tr');
				tr.find('.btn-run-task').addClass('hide');
				tr.find('.btn-cancel-task').removeClass('hide');
				tr.find('.btn-log').addClass('hide');
				tr.find('.next-run-info').addClass('hide');
			},
			onTaskCompleted: function (taskId, el) {
				var tr = el.closest('tr'),
					profileId = tr.data('profile-id');

				tr.find('.btn-run-task').removeClass('hide');
				tr.find('.btn-cancel-task').addClass('hide');
				tr.find('.btn-log').removeClass('hide');

				$.ajax({
					cache: false,
					global: false,
					type: 'POST',
					url: '@Url.Action("GetTaskRunInfo", "ScheduleTask")',
					data: { id: taskId },
					success: function (data) {
						tr.find('.next-run-info').html(data.nextRunHtml).removeClass("hide");
						tr.find('.last-run-info').html(data.lastRunHtml);
					}
				});

				$.get('@Url.Action("ProfileListDetails")?profileId=' + profileId, function (response) {
					$('#ProfileImportResult' + profileId).html(response.importResult || '');
				});
			}
		});
	});
</script>

SmartStoreNET-4.x/src/Presentation/SmartStore.Web/Administration/Views/Import/ProfileImportResult.cshtml
@using SmartStore.Services.DataExchange.Import;
@model SerializableImportResult
@{
	Layout = null;
}
<div class="py-2">
	<div>
		<span>@T("Admin.Common.TotalRows"):</span>
		<span class="muted">@Model.TotalRecords</span> &middot;
		<span>@T("Admin.Common.Skipped"):</span> <span class="muted">@Model.SkippedRecords</span>
	</div>
	<div>
		<span>@T("Admin.Common.NewRecords"):</span> <span class="muted">@Model.NewRecords</span> &middot;
		<span>@T("Admin.Common.Updated"):</span> <span class="muted">@Model.ModifiedRecords</span>
	</div>
	<div>
		<span>@T("Admin.Common.Errors"):</span> <span class="muted">@Model.Errors</span> &middot;
		<span>@T("Admin.Common.Warnings"):</span> <span class="muted">@Model.Warnings</span>
	</div>
</div>

SmartStoreNET-4.x/src/Presentation/SmartStore.Web/Administration/Views/Import/_ColumnMappings.cshtml
@using SmartStore.Admin.Models.DataExchange;
@model ImportProfileModel
@{
	var delete = T("Common.Delete");
	var ignore = @T("Admin.Common.Ignore");
	var selectTargetProperty = T("Admin.DataExchange.Import.SelectTargetProperty");
}

<div>
	<table class="adminContent">
		<tr class="adminSeparator">
			<td>
				<div class="admin-config-group">
					<div class="title">@T("Admin.DataExchange.Import.ColumnMapping")</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="alert alert-info alert-dismissible">
					@Html.Raw(T("Admin.DataExchange.ColumnMapping.Note"))
					<button type="button" class="close" data-dismiss="alert">&times;</button>
				</div>

				@if (Model.ColumnMappings.Any())
				{
					<button id="ResetColumnMappings" type="button" class="btn btn-secondary btn-to-danger" data-url="@Url.Action("ResetColumnMappings", new { id = Model.Id })">
						<i class="fa fa-sync"></i>
						<span>@T("Admin.Common.Clear")</span>
					</button>
				}
			</td>
		</tr>
	</table>
</div>

<div id="PropertyMappingTemplate" class="d-none">
	<div class="mapping-edit form-row">
		<div class="col">
			<select class="form-control select-property noskin">
			@foreach (var property in Model.AvailableEntityProperties)
			{
					<option value="@property.Property" data-defaultdisabled="@(property.IsDefaultDisabled ? "1" : "0")">@property.PropertyDescription</option>
			}
			</select>
		</div>
		<div class="col-auto">
			<button type="button" class="btn btn-warning mapping-apply btn-icon"><i class="fa fa-check"></i></button>
			<button type="button" class="btn btn-outline-secondary btn-to-danger mapping-cancel btn-icon"><i class="fa fa-times"></i></button>
		</div>
	</div>
</div>

<div id="ColumnMappingTemplate" class="d-none">
	<div class="mapping-edit form-row">
		<div class="col">
			<select class="form-control select-column noskin" data-placeholder="@ignore">
				<option></option>
				@foreach (var column in Model.AvailableSourceColumns)
				{
					<option value="@column.Column">@column.PropertyDescription</option>
				}
			</select>
		</div>
		<div class="col-auto">
			<button type="button" class="btn btn-warning mapping-apply btn-icon"><i class="fa fa-check"></i></button>
			<button type="button" class="btn btn-outline-secondary btn-to-danger mapping-cancel btn-icon"><i class="fa fa-times"></i></button>
		</div>
	</div>
</div>

@*Add new field mapping*@ 
<div id="AddMappingTemplate" class="d-none">
	<table>
		<tbody>
			<tr class="column-mapping-new">
				<td>
					<div class="mapping-item mapping-property">
						<input type="hidden" class="input-property" value="" />
						<div class="item-inner d-none">
							<span class="property-icon pr-2">
								<i class="text-success fa fa-fw"></i>
							</span>
							<span class="left-label"></span>
							<span class="muted right-label ml-auto"></span>
						</div>
						<select class="form-control select-property noskin" data-placeholder="@selectTargetProperty">
							<option></option>
							@foreach (var property in Model.AvailableEntityProperties)
							{
								<option value="@property.Property" data-defaultdisabled="@(property.IsDefaultDisabled ? "1" : "0")">@property.PropertyDescription</option>
							}
						</select>
					</div>
				</td>
				<td>
					<div class="mapping-item mapping-column">
						<input type="hidden" class="input-column" value="" />
						<div class="item-inner d-none">
							<span class="left-label"></span>
						</div>
						<select class="form-control select-column noskin" data-placeholder="@ignore">
							<option></option>
							@foreach (var column in Model.AvailableSourceColumns)
							{
								<option value="@column.Column">@column.PropertyDescription</option>
							}
						</select>
					</div>
				</td>
				<td>
					<input type="text" class="form-control input-default" value="" disabled="disabled" />
				</td>
				<td class="omega">
					<button type="button" class="btn btn-block btn-primary mapping-add" disabled="disabled" title="@T("Common.AddNew")">
						<i class="fa fa-plus"></i>
						<span class="mapping-button-label">
							@T("Common.AddNew")
						</span>
					</button>
					<button type="button" class="btn btn-block btn-danger hide mapping-delete" title="@delete">
						<i class="far fa-trash-alt"></i>
						<span class="mapping-button-label">
							@delete
						</span>
					</button>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<div id="ImportColumnMappings" class="adminContent table-responsive mt-3">
	<table class="table table-striped admin-table column-mapping" data-maxindex="@Model.ColumnMappings.Count">
		<thead>
			<tr>
				<th class="column-one">@T("Admin.DataExchange.ColumnMapping.EntityProperty")</th>
				<th class="column-two">@T("Admin.DataExchange.ColumnMapping.ImportField")</th>			
				<th class="column-three">@T("Admin.DataExchange.ColumnMapping.DefaultValue")</th>
				<th class="column-four">&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var mapping in Model.ColumnMappings)
			{
				var index = Model.ColumnMappings.IndexOf(mapping) + 1;
				<tr>
					<td>
						<div class="mapping-item mapping-property">
							<input type="hidden" name="ColumnMapping.Property.@(index)" value="@mapping.Property" />
							<div class="item-inner">
								<span class="property-icon pr-2">
									<i class="text-success fa fa-fw @(mapping.Property.EmptyNull().EndsWith("]") ? "fa-globe" : "fa-unlink")"></i>
								</span>
								@if (mapping.PropertyDescription.Length > Model.MaxMappingLabelTextLength)
								{
									<span class="left-label" title="@mapping.PropertyDescription">@(mapping.PropertyDescription.Substring(0, Model.MaxMappingLabelTextLength))…</span>
								}
								else
								{
									<span class="left-label">@mapping.PropertyDescription</span>
								}
								<span class="muted right-label ml-auto">@mapping.Property</span>
							</div>
						</div>
					</td>
					<td>
						<div class="mapping-item mapping-column">
							<input type="hidden" name="ColumnMapping.Column.@(index)" value="@mapping.Column" />
							<div class="item-inner">
								<span class="left-label">
									@if (mapping.Column.HasValue())
									{
										@mapping.Column
									}
									else
									{
										<span class="muted">@ignore</span>
									}
								</span>
							</div>
						</div>
					</td>
					<td>
						<input type="text" name="ColumnMapping.Default.@(index)" class="form-control input-default" value="@mapping.Default" 
							   @Html.Attr("disabled", "disabled", mapping.IsDefaultDisabled || !mapping.Column.HasValue()) />
					</td>
					<td align="right" class="omega">
						<button type="button" class="btn btn-block btn-danger mapping-delete" title="@delete">
							<span class="mapping-button-label">@delete</span>
						</button>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>